# .streamlit/secrets.toml
SUPABASE_URL = "https://wslsayfkmezgtvlgzmco.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzbHNheWZrbWV6Z3R2bGd6bWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODE4OTAsImV4cCI6MjA3MTk1Nzg5MH0.zqL9HxguIApfNa2Q7OoB4pdWSIPCJnbW4f_ZdBX0I7s"
# optional: admin invite code for creating admin accounts in-app
ADMIN_INVITE_CODE = "MU-ADMIN-2025"
